plugin: aws_ec2

aws_access_key: AKIARVQWXIQJOWQU73O7
aws_secret_key: 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 

regions:
  - us-east-1

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
